#Configuracion del puerto para el api-ms-appreforma
server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.value}:${server.port}

#Asignacion del nombre del microservicio
spring:
  application:
    name: api-ms-appreforma
  #Configuracion de la BD- login - usuario
  datasource:
    url: jdbc:postgresql://localhost:54321/appReforma
    username: postgres
    password: 11073026
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #Configuracion para la serializacion del TypeFetch : LAZY O EAGER
  jackson:
    serialization:
      fail-on-empty-beans: false
  #Configuracion para crear un registro de migraciones en la BD
  flyway:
    baselineOnMigrate: true