DELETE FROM catalogo_nacionalidades;

ALTER SEQUENCE catalogo_nacionalidades_nacionalidadid_seq restart 1;

INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (1, 'AFGANO', 'AFGANISTÁN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (2, 'ALBANÉS', 'ALBANIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (3, 'ALEMÁN/ GERMANO', 'ALEMANIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (4, 'ANDORRANO', 'ANDORRA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (5, 'ANGOLEÑO', 'ANGOLA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (6, 'ARGELIANO', 'ARGELIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (7, 'ARGENTINO', 'ARGENTINA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (8, 'ARMENIO', 'ARMENIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (9, 'AUSTRALIANO', 'AUSTRALIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (10, 'AUSTRIACO', 'AUSTRIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (11, 'AZERBAIYANO', 'AZERBAIYÁN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (12, 'BAHAMÉS', 'BAHAMAS');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (13, 'BANGLADESÍ', 'BANGLADESH');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (14, 'BARBADENSE', 'BARBADOS');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (15, 'BELGA', 'BÉLGICA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (16, 'BELICEÑO', 'BELICE');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (17, 'BIELORRUSO', 'BIELORRUSIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (18, 'BIRMANO', 'MYANMAR');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (19, 'BOLIVIANO', 'BOLIVIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (20, 'BOSNIO/ BOSNÍACO', 'BOSNIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (21, 'BOTSUANO', 'BOTSUANA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (22, 'BRASILEÑO', 'BRASIL');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (23, 'BRITÁNICO', 'GRAN BRETAÑA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (24, 'BÚLGARO', 'BULGARIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (25, 'BURUNDÉS', 'BURUNDI');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (26, 'BUTANÉS', 'BUTÁN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (27, 'CAMBOYANO', 'CAMBOYA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (28, 'CAMERUNÉS', 'CAMERÚN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (29, 'CANADIENSE', 'CANADÁ');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (30, 'CHADIANO', 'CHAD');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (31, 'CHECO', 'CHEQUIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (32, 'CHILENO', 'CHILE');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (33, 'CHINO', 'CHINA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (34, 'CHIPRIOTA', 'CHIPRE');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (35, 'COLOMBIANO', 'COLOMBIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (36, 'CONGOLEÑO', 'CONGO');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (37, 'COREANO', 'COREA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (38, 'COSTARRICENSE', 'COSTA RICA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (39, 'CROATA', 'CROACIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (40, 'CUBANO', 'CUBA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (41, 'DANÉS', 'DINAMARCA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (42, 'DOMINICANO', 'R. DOMINICANA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (43, 'ECUATOGUINEANO', 'GUINEA ECUATORIAL');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (44, 'ECUATORIANO', 'ECUADOR');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (45, 'EGIPCIO', 'EGIPTO');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (46, 'ESCOCÉS', 'ESCOCIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (47, 'ESLOVACO', 'ESLOVAQUIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (48, 'ESLOVENO', 'ESLOVENIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (49, 'ESPAÑOL', 'ESPAÑA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (50, 'ESRILANQUÉS', 'SRI LANKA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (51, 'ESTADOUNIDENSE/ NORTEAMERICANO', 'ESTADOS UNIDOS');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (52, 'ETÍOPE', 'ETIOPÍA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (53, 'FILIPINO', 'FILIPINAS');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (54, 'FINLANDÉS', 'FINLANDIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (55, 'FRANCÉS', 'FRANCIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (56, 'GABONÉS', 'GABÓN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (57, 'GALÉS', 'GALES');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (58, 'GAMBIANO', 'GAMBIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (59, 'GEORGIANO', 'GEORGIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (60, 'GHANÉS', 'GHANA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (61, 'GIBRALTAREÑO', 'GIBRALTAR');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (62, 'GRIEGO', 'GRECIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (63, 'GUATEMALTECO', 'GUATEMALA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (64, 'GUERNSE', 'GUERNSEY');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (65, 'GUYANÉS', 'GUYANA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (66, 'HOLANDÉS/ NEERLANDÉS', 'HOLANDA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (67, 'HONDUREÑO', 'HONDURAS');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (68, 'HÚNGARO/ MAGIAR', 'HUNGRÍA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (69, 'INDIO', 'INDIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (70, 'INDONESIO', 'INDONESIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (71, 'INGLÉS', 'INGLATERRA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (72, 'IRANÍ', 'IRÁN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (73, 'IRAQUÍ', 'IRAK');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (74, 'IRLANDÉS', 'IRLANDA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (75, 'ISLANDÉS', 'ISLANDIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (76, 'ISRAELÍ', 'ISRAEL');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (77, 'ITALIANO', 'ITALIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (78, 'JAPONÉS/ NIPÓN', 'JAPÓN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (79, 'JORDANO', 'JORDANIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (80, 'KAZAJO', 'KAZAJISTÁN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (81, 'KENIANO', 'KENIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (82, 'KUWAITÍ', 'KUWAIT');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (83, 'LAOSIANO', 'LAOS');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (84, 'LIBIO', 'LIBIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (85, 'LIECHTENSTEIN', 'LIECHTENSTEIN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (86, 'LUXEMBURGUÉS', 'LUXEMBURGO');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (87, 'MAGREBÍ', 'MAGREB');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (88, 'MALGACHE', 'MADAGASCAR');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (89, 'MALIENSE', 'MALI');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (90, 'MARFILENSE', 'COSTA DE MARFIL');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (91, 'MARROQUÍ', 'MARRUECOS');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (92, 'MAURITANO', 'MAURITANIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (93, 'MEXICANA', 'MÉXICO');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (94, 'MOLDAVO', 'MOLDAVIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (95, 'MONEGASCO', 'MÓNACO');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (96, 'MONGOL', 'MONGOLIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (97, 'MONTENEGRINO', 'MONTENEGRO');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (98, 'MOZAMBIQUEÑO', 'MOZAMBIQUE');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (99, 'NAMIBIO', 'NAMIBIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (100, 'NEPALÉS', 'NEPAL');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (101, 'NICARAGÜENSE', 'NUCARAGUA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (102, 'NIGERIANO', 'NIGERIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (103, 'NIGERINO', 'NÍGER');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (104, 'NORCOREANO', 'COREA DEL NORTE');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (105, 'NORCOREANO', 'COREA DEL NORTE');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (106, 'NORUEGO', 'NORUEGA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (107, 'OMANÍ', 'OMÁN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (108, 'PALESTINO', 'PALESTINA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (109, 'PANAMEÑO', 'PANAMÁ');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (110, 'PAQUISTANÍ', 'PAKISTÁN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (111, 'PARAGUAYO', 'PARAGUAY');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (112, 'PERSA', 'PERSIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (113, 'PERUANO', 'PERÚ');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (114, 'POLACO', 'POLONIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (115, 'PORTUGUÉS/ LUSO/ LUSITANIO', 'PORTUGAL');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (116, 'PUERTORRIQUEÑO', 'PUERTO RICO');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (117, 'RUANDÉS', 'RUANDA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (118, 'RUMANO', 'RUMANIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (119, 'RUSO', 'RUSIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (120, 'SALVADOREÑO', 'EL SALVADOR');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (121, 'SANMARINENSE', 'SAN MARINO');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (122, 'SAUDÍ', 'ARABIA SAUDÍ');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (123, 'SENEGALÉS', 'SENEGAL');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (124, 'SERBIO', 'SERBIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (125, 'SIRIO', 'SIRIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (126, 'SOMALÍ', 'SOMALIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (127, 'SUAZI', 'SUAZILANDIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (128, 'SUDANÉS', 'SUDÁN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (129, 'SUECO', 'SUECIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (130, 'SUIZO', 'SUIZA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (131, 'TAILANDÉS', 'TAILANDIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (132, 'TANZANO', 'TANZANIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (133, 'TOGOLÉS', 'TOGO');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (134, 'TRINITARIO', 'TRINIDAD Y TOBAGO');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (135, 'TRINITARIO', 'TRINIDAD Y TOBAGO');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (136, 'TUNECINO', 'TÚNEZ');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (137, 'TURCO', 'TURQUÍA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (138, 'UCRANIANO', 'UCRANIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (139, 'UGANDÉS', 'UGANDA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (140, 'URUGUAYO', 'URUGUAY');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (141, 'UZBEKO', 'UZBEKISTÁN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (142, 'VENEZOLANO', 'VENEZUELA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (143, 'VIETNAMITA', 'VIETNAM');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (144, 'YEMENÍ', 'YEMEN');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (145, 'YUGOSLAVO', 'YUGOSLAVIA');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (146, 'ZAIREÑO', 'ZAIRE');
INSERT INTO catalogo_nacionalidades (nacionalidadid, nacionalidad, pais) VALUES (147, 'ZAMBIANO', 'ZAMBIA');

SELECT SETVAL('catalogo_nacionalidades_nacionalidadid_seq',(SELECT MAX(nacionalidadid) FROM catalogo_nacionalidades));
